// <auto-generated />
using CRM.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250505201914_InitialScaffold")]
    partial class InitialScaffold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("CRM.Repositories.Entities.Generals.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            FullName = "Administrator",
                            Password = "5ab598c2af4a0d05a5cd66885fb02605151f4d18b90e557d526e36583eb5944a",
                            Phone = "",
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "manager@example.com",
                            FullName = "Manager",
                            Password = "5ab598c2af4a0d05a5cd66885fb02605151f4d18b90e557d526e36583eb5944a",
                            Phone = "",
                            UserName = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Email = "reader@example.com",
                            FullName = "Reader",
                            Password = "5ab598c2af4a0d05a5cd66885fb02605151f4d18b90e557d526e36583eb5944a",
                            Phone = "",
                            UserName = "Reader"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
