//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Repositories.ContextExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SeederResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeederResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Repositories.ContextExtension.SeederResource", typeof(SeederResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;UserName&quot;:&quot;Admin&quot;,&quot;FullName&quot;:&quot;Administrator&quot;,&quot;Password&quot;:&quot;5ab598c2af4a0d05a5cd66885fb02605151f4d18b90e557d526e36583eb5944a&quot;,&quot;Email&quot;:&quot;admin@example.com&quot;,&quot;Phone&quot;:&quot;&quot;,&quot;LastLogin&quot;:&quot;2022-08-31 12:30:50&quot;,&quot;Status&quot;:0,&quot;RoleId&quot;:1},{&quot;Id&quot;:2,&quot;UserName&quot;:&quot;Manager&quot;,&quot;FullName&quot;:&quot;Manager&quot;,&quot;Password&quot;:&quot;5ab598c2af4a0d05a5cd66885fb02605151f4d18b90e557d526e36583eb5944a&quot;,&quot;Email&quot;:&quot;manager@example.com&quot;,&quot;Phone&quot;:&quot;&quot;,&quot;LastLogin&quot;:&quot;2022-08-31 12:30:50&quot;,&quot;Status&quot;:0,&quot;RoleId&quot;:2},{&quot;Id&quot;:3,&quot;UserName&quot;:&quot;Reader&quot;,&quot;FullName&quot;:&quot;Reader&quot;,&quot;Password [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
